name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '**/*.md'
      - '!.github/workflows/ci.yml'
  push:
    branches:
      - main
      - "renovate/**"
    paths-ignore:
      - '**/*.md'
      - '!.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: ./.github/actions/pnpm
      - uses: Boshen/setup-rust@main
        with:
          cache-key: warm
      - run: find fixtures/pnp
      - uses: actions/upload-artifact@v4
        name: pnp.cjs upload
        with:
          name: pnp-${{ matrix.os }}.cjs
          path: |
            ./fixtures/pnp/.pnp.cjs
          if-no-files-found: error
          include-hidden-files: true
      - run: cargo test --all-features pnp -- --nocapture
