name: Release Full

on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: "Release Npm Tag"
        required: true
        default: "latest"
        options:
          - canary
          - nightly
          - latest
          - beta
          - alpha
      test:
        type: boolean
        description: "Run tests before release"
        required: true
        default: true
      dry_run:
        type: boolean
        description: "DryRun release"
        required: true
        default: false
      push_tags:
        type: boolean
        description: "push tags to github"
        required: true
        default: true

permissions:
  # To publish packages with provenance
  id-token: write
  # Allow commenting on issues for `reusable-build.yml`
  issues: write

jobs:
  build:
    strategy:
      fail-fast: false # Build and test everything so we can look at all the errors
      matrix:
        array:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
          - target: i686-pc-windows-msvc
          - target: x86_64-pc-windows-msvc
          - target: aarch64-pc-windows-msvc
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: ${{ matrix.array.target }}
      test: ${{ inputs.test }}
      profile: "release"

  release:
    name: Release
    permissions:
      contents: write
      # To publish packages with provenance
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # This makes Actions fetch only one branch to release
          fetch-depth: 1

      - name: Pnpm Setup
        uses: ./.github/actions/pnpm/setup

      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts

      - name: Build node packages
        run: pnpm run build:js

      - name: Move artifacts
        run: node scripts/build-npm.cjs

      - name: Show binding packages
        run: ls -R npm

      - name: Link optional dependencies
        run: pnpm install --no-frozen-lockfile

#      - name: Release Full
#        run: |
#          ./x publish stable --tag ${{inputs.tag}} ${{inputs.dry_run && '--dry-run' || '--no-dry-run'}} ${{inputs.push_tags && '--push-tags' || '--no-push-tags'}}
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#          REPOSITORY: ${{ github.repository }}
#          REF: ${{ github.ref }}
#          ONLY_RELEASE_TAG: true
