name: Release Plz

on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        description: "Full Commit SHA to release"
      dry_run:
        type: boolean
        description: "DryRun release"
        required: false
        default: false

permissions:
  id-token: write

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    environment: crate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Boshen/setup-rust@main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: warm

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish
        run: cargo publish
        if: ${{ !inputs.dry_run }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Dry Run Publish
        run: cargo publish --dry-run
        if: inputs.dry_run
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Push tag
        run: git push origin ${{ inputs.commit }}